// Code generated by protoc-gen-go. DO NOT EDIT.
// source: home/home.proto

package university_circles_srv_home

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PublishMsg struct {
	Uid                  string        `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Content              string        `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Pictures             []*PictureReq `protobuf:"bytes,3,rep,name=pictures,proto3" json:"pictures,omitempty"`
	Poi                  *Poi          `protobuf:"bytes,4,opt,name=poi,proto3" json:"poi,omitempty"`
	Type                 string        `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	MsgType              int64         `protobuf:"varint,6,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	LinkInfo             *LinkInfo     `protobuf:"bytes,7,opt,name=LinkInfo,proto3" json:"LinkInfo,omitempty"`
	Video                *Video        `protobuf:"bytes,8,opt,name=video,proto3" json:"video,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PublishMsg) Reset()         { *m = PublishMsg{} }
func (m *PublishMsg) String() string { return proto.CompactTextString(m) }
func (*PublishMsg) ProtoMessage()    {}
func (*PublishMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{0}
}

func (m *PublishMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishMsg.Unmarshal(m, b)
}
func (m *PublishMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishMsg.Marshal(b, m, deterministic)
}
func (m *PublishMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishMsg.Merge(m, src)
}
func (m *PublishMsg) XXX_Size() int {
	return xxx_messageInfo_PublishMsg.Size(m)
}
func (m *PublishMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PublishMsg proto.InternalMessageInfo

func (m *PublishMsg) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *PublishMsg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PublishMsg) GetPictures() []*PictureReq {
	if m != nil {
		return m.Pictures
	}
	return nil
}

func (m *PublishMsg) GetPoi() *Poi {
	if m != nil {
		return m.Poi
	}
	return nil
}

func (m *PublishMsg) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PublishMsg) GetMsgType() int64 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *PublishMsg) GetLinkInfo() *LinkInfo {
	if m != nil {
		return m.LinkInfo
	}
	return nil
}

func (m *PublishMsg) GetVideo() *Video {
	if m != nil {
		return m.Video
	}
	return nil
}

type PublishMsgResponse struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MsgType              int64       `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Content              string      `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Pictures             []*Picture  `protobuf:"bytes,4,rep,name=pictures,proto3" json:"pictures,omitempty"`
	Poi                  *Poi        `protobuf:"bytes,5,opt,name=poi,proto3" json:"poi,omitempty"`
	Type                 string      `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Status               string      `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CommentCount         int64       `protobuf:"varint,8,opt,name=commentCount,proto3" json:"commentCount,omitempty"`
	ShareCount           int64       `protobuf:"varint,9,opt,name=shareCount,proto3" json:"shareCount,omitempty"`
	LikeCount            int64       `protobuf:"varint,10,opt,name=likeCount,proto3" json:"likeCount,omitempty"`
	LinkInfo             *LinkInfo   `protobuf:"bytes,11,opt,name=LinkInfo,proto3" json:"LinkInfo,omitempty"`
	CreatedAt            string      `protobuf:"bytes,12,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	User                 *EsUserInfo `protobuf:"bytes,13,opt,name=user,proto3" json:"user,omitempty"`
	IsCommentForbidden   bool        `protobuf:"varint,14,opt,name=isCommentForbidden,proto3" json:"isCommentForbidden,omitempty"`
	Liked                bool        `protobuf:"varint,15,opt,name=liked,proto3" json:"liked,omitempty"`
	Collected            bool        `protobuf:"varint,16,opt,name=collected,proto3" json:"collected,omitempty"`
	OrderId              int64       `protobuf:"varint,17,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Video                *Video      `protobuf:"bytes,18,opt,name=video,proto3" json:"video,omitempty"`
	IsFollow             bool        `protobuf:"varint,19,opt,name=isFollow,proto3" json:"isFollow,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PublishMsgResponse) Reset()         { *m = PublishMsgResponse{} }
func (m *PublishMsgResponse) String() string { return proto.CompactTextString(m) }
func (*PublishMsgResponse) ProtoMessage()    {}
func (*PublishMsgResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{1}
}

func (m *PublishMsgResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishMsgResponse.Unmarshal(m, b)
}
func (m *PublishMsgResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishMsgResponse.Marshal(b, m, deterministic)
}
func (m *PublishMsgResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishMsgResponse.Merge(m, src)
}
func (m *PublishMsgResponse) XXX_Size() int {
	return xxx_messageInfo_PublishMsgResponse.Size(m)
}
func (m *PublishMsgResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishMsgResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishMsgResponse proto.InternalMessageInfo

func (m *PublishMsgResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PublishMsgResponse) GetMsgType() int64 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *PublishMsgResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PublishMsgResponse) GetPictures() []*Picture {
	if m != nil {
		return m.Pictures
	}
	return nil
}

func (m *PublishMsgResponse) GetPoi() *Poi {
	if m != nil {
		return m.Poi
	}
	return nil
}

func (m *PublishMsgResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PublishMsgResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PublishMsgResponse) GetCommentCount() int64 {
	if m != nil {
		return m.CommentCount
	}
	return 0
}

func (m *PublishMsgResponse) GetShareCount() int64 {
	if m != nil {
		return m.ShareCount
	}
	return 0
}

func (m *PublishMsgResponse) GetLikeCount() int64 {
	if m != nil {
		return m.LikeCount
	}
	return 0
}

func (m *PublishMsgResponse) GetLinkInfo() *LinkInfo {
	if m != nil {
		return m.LinkInfo
	}
	return nil
}

func (m *PublishMsgResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *PublishMsgResponse) GetUser() *EsUserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *PublishMsgResponse) GetIsCommentForbidden() bool {
	if m != nil {
		return m.IsCommentForbidden
	}
	return false
}

func (m *PublishMsgResponse) GetLiked() bool {
	if m != nil {
		return m.Liked
	}
	return false
}

func (m *PublishMsgResponse) GetCollected() bool {
	if m != nil {
		return m.Collected
	}
	return false
}

func (m *PublishMsgResponse) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *PublishMsgResponse) GetVideo() *Video {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *PublishMsgResponse) GetIsFollow() bool {
	if m != nil {
		return m.IsFollow
	}
	return false
}

type PublishMsgComment struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TargetId             string             `protobuf:"bytes,2,opt,name=targetId,proto3" json:"targetId,omitempty"`
	Content              string             `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Pictures             []*Picture         `protobuf:"bytes,4,rep,name=pictures,proto3" json:"pictures,omitempty"`
	Liked                bool               `protobuf:"varint,5,opt,name=liked,proto3" json:"liked,omitempty"`
	Type                 string             `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Status               string             `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Level                int64              `protobuf:"varint,8,opt,name=level,proto3" json:"level,omitempty"`
	ReplyCount           int64              `protobuf:"varint,9,opt,name=replyCount,proto3" json:"replyCount,omitempty"`
	LikeCount            int64              `protobuf:"varint,10,opt,name=likeCount,proto3" json:"likeCount,omitempty"`
	ReplyToComment       *PublishMsgComment `protobuf:"bytes,11,opt,name=replyToComment,proto3" json:"replyToComment,omitempty"`
	UrlsInText           []*UrlsInText      `protobuf:"bytes,12,rep,name=urlsInText,proto3" json:"urlsInText,omitempty"`
	CreatedAt            string             `protobuf:"bytes,13,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	User                 *EsUserInfo        `protobuf:"bytes,14,opt,name=user,proto3" json:"user,omitempty"`
	OrderId              int64              `protobuf:"varint,15,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PublishMsgComment) Reset()         { *m = PublishMsgComment{} }
func (m *PublishMsgComment) String() string { return proto.CompactTextString(m) }
func (*PublishMsgComment) ProtoMessage()    {}
func (*PublishMsgComment) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{2}
}

func (m *PublishMsgComment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishMsgComment.Unmarshal(m, b)
}
func (m *PublishMsgComment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishMsgComment.Marshal(b, m, deterministic)
}
func (m *PublishMsgComment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishMsgComment.Merge(m, src)
}
func (m *PublishMsgComment) XXX_Size() int {
	return xxx_messageInfo_PublishMsgComment.Size(m)
}
func (m *PublishMsgComment) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishMsgComment.DiscardUnknown(m)
}

var xxx_messageInfo_PublishMsgComment proto.InternalMessageInfo

func (m *PublishMsgComment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PublishMsgComment) GetTargetId() string {
	if m != nil {
		return m.TargetId
	}
	return ""
}

func (m *PublishMsgComment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PublishMsgComment) GetPictures() []*Picture {
	if m != nil {
		return m.Pictures
	}
	return nil
}

func (m *PublishMsgComment) GetLiked() bool {
	if m != nil {
		return m.Liked
	}
	return false
}

func (m *PublishMsgComment) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PublishMsgComment) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PublishMsgComment) GetLevel() int64 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *PublishMsgComment) GetReplyCount() int64 {
	if m != nil {
		return m.ReplyCount
	}
	return 0
}

func (m *PublishMsgComment) GetLikeCount() int64 {
	if m != nil {
		return m.LikeCount
	}
	return 0
}

func (m *PublishMsgComment) GetReplyToComment() *PublishMsgComment {
	if m != nil {
		return m.ReplyToComment
	}
	return nil
}

func (m *PublishMsgComment) GetUrlsInText() []*UrlsInText {
	if m != nil {
		return m.UrlsInText
	}
	return nil
}

func (m *PublishMsgComment) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *PublishMsgComment) GetUser() *EsUserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *PublishMsgComment) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

type PictureReq struct {
	ImageId              string   `protobuf:"bytes,1,opt,name=imageId,proto3" json:"imageId,omitempty"`
	Width                int64    `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height               int64    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Format               string   `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PictureReq) Reset()         { *m = PictureReq{} }
func (m *PictureReq) String() string { return proto.CompactTextString(m) }
func (*PictureReq) ProtoMessage()    {}
func (*PictureReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{3}
}

func (m *PictureReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PictureReq.Unmarshal(m, b)
}
func (m *PictureReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PictureReq.Marshal(b, m, deterministic)
}
func (m *PictureReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PictureReq.Merge(m, src)
}
func (m *PictureReq) XXX_Size() int {
	return xxx_messageInfo_PictureReq.Size(m)
}
func (m *PictureReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PictureReq.DiscardUnknown(m)
}

var xxx_messageInfo_PictureReq proto.InternalMessageInfo

func (m *PictureReq) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

func (m *PictureReq) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *PictureReq) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *PictureReq) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

type Picture struct {
	ThumbnailUrl         string   `protobuf:"bytes,1,opt,name=thumbnailUrl,proto3" json:"thumbnailUrl,omitempty"`
	MiddlePicUrl         string   `protobuf:"bytes,2,opt,name=middlePicUrl,proto3" json:"middlePicUrl,omitempty"`
	PicUrl               string   `protobuf:"bytes,3,opt,name=picUrl,proto3" json:"picUrl,omitempty"`
	Format               string   `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	Width                int64    `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height               int64    `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Picture) Reset()         { *m = Picture{} }
func (m *Picture) String() string { return proto.CompactTextString(m) }
func (*Picture) ProtoMessage()    {}
func (*Picture) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{4}
}

func (m *Picture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Picture.Unmarshal(m, b)
}
func (m *Picture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Picture.Marshal(b, m, deterministic)
}
func (m *Picture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Picture.Merge(m, src)
}
func (m *Picture) XXX_Size() int {
	return xxx_messageInfo_Picture.Size(m)
}
func (m *Picture) XXX_DiscardUnknown() {
	xxx_messageInfo_Picture.DiscardUnknown(m)
}

var xxx_messageInfo_Picture proto.InternalMessageInfo

func (m *Picture) GetThumbnailUrl() string {
	if m != nil {
		return m.ThumbnailUrl
	}
	return ""
}

func (m *Picture) GetMiddlePicUrl() string {
	if m != nil {
		return m.MiddlePicUrl
	}
	return ""
}

func (m *Picture) GetPicUrl() string {
	if m != nil {
		return m.PicUrl
	}
	return ""
}

func (m *Picture) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Picture) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Picture) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Poi struct {
	Location             []*Location `protobuf:"bytes,1,rep,name=location,proto3" json:"location,omitempty"`
	Countryname          string      `protobuf:"bytes,2,opt,name=countryname,proto3" json:"countryname,omitempty"`
	PoiId                string      `protobuf:"bytes,3,opt,name=poiId,proto3" json:"poiId,omitempty"`
	FormattedAddress     string      `protobuf:"bytes,4,opt,name=formattedAddress,proto3" json:"formattedAddress,omitempty"`
	Cityname             string      `protobuf:"bytes,5,opt,name=cityname,proto3" json:"cityname,omitempty"`
	Pname                string      `protobuf:"bytes,6,opt,name=pname,proto3" json:"pname,omitempty"`
	Name                 string      `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Poi) Reset()         { *m = Poi{} }
func (m *Poi) String() string { return proto.CompactTextString(m) }
func (*Poi) ProtoMessage()    {}
func (*Poi) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{5}
}

func (m *Poi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Poi.Unmarshal(m, b)
}
func (m *Poi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Poi.Marshal(b, m, deterministic)
}
func (m *Poi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Poi.Merge(m, src)
}
func (m *Poi) XXX_Size() int {
	return xxx_messageInfo_Poi.Size(m)
}
func (m *Poi) XXX_DiscardUnknown() {
	xxx_messageInfo_Poi.DiscardUnknown(m)
}

var xxx_messageInfo_Poi proto.InternalMessageInfo

func (m *Poi) GetLocation() []*Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Poi) GetCountryname() string {
	if m != nil {
		return m.Countryname
	}
	return ""
}

func (m *Poi) GetPoiId() string {
	if m != nil {
		return m.PoiId
	}
	return ""
}

func (m *Poi) GetFormattedAddress() string {
	if m != nil {
		return m.FormattedAddress
	}
	return ""
}

func (m *Poi) GetCityname() string {
	if m != nil {
		return m.Cityname
	}
	return ""
}

func (m *Poi) GetPname() string {
	if m != nil {
		return m.Pname
	}
	return ""
}

func (m *Poi) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Location struct {
	Loc                  float64  `protobuf:"fixed64,1,opt,name=loc,proto3" json:"loc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{6}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLoc() float64 {
	if m != nil {
		return m.Loc
	}
	return 0
}

type LinkInfo struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	PictureUrl           string   `protobuf:"bytes,2,opt,name=pictureUrl,proto3" json:"pictureUrl,omitempty"`
	LinkUrl              string   `protobuf:"bytes,3,opt,name=linkUrl,proto3" json:"linkUrl,omitempty"`
	Source               string   `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Audio                *Audio   `protobuf:"bytes,5,opt,name=audio,proto3" json:"audio,omitempty"`
	Video                *Video   `protobuf:"bytes,6,opt,name=video,proto3" json:"video,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkInfo) Reset()         { *m = LinkInfo{} }
func (m *LinkInfo) String() string { return proto.CompactTextString(m) }
func (*LinkInfo) ProtoMessage()    {}
func (*LinkInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{7}
}

func (m *LinkInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkInfo.Unmarshal(m, b)
}
func (m *LinkInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkInfo.Marshal(b, m, deterministic)
}
func (m *LinkInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkInfo.Merge(m, src)
}
func (m *LinkInfo) XXX_Size() int {
	return xxx_messageInfo_LinkInfo.Size(m)
}
func (m *LinkInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LinkInfo proto.InternalMessageInfo

func (m *LinkInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *LinkInfo) GetPictureUrl() string {
	if m != nil {
		return m.PictureUrl
	}
	return ""
}

func (m *LinkInfo) GetLinkUrl() string {
	if m != nil {
		return m.LinkUrl
	}
	return ""
}

func (m *LinkInfo) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *LinkInfo) GetAudio() *Audio {
	if m != nil {
		return m.Audio
	}
	return nil
}

func (m *LinkInfo) GetVideo() *Video {
	if m != nil {
		return m.Video
	}
	return nil
}

type UrlsInText struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	OriginalUrl          string   `protobuf:"bytes,2,opt,name=originalUrl,proto3" json:"originalUrl,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UrlsInText) Reset()         { *m = UrlsInText{} }
func (m *UrlsInText) String() string { return proto.CompactTextString(m) }
func (*UrlsInText) ProtoMessage()    {}
func (*UrlsInText) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{8}
}

func (m *UrlsInText) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UrlsInText.Unmarshal(m, b)
}
func (m *UrlsInText) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UrlsInText.Marshal(b, m, deterministic)
}
func (m *UrlsInText) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UrlsInText.Merge(m, src)
}
func (m *UrlsInText) XXX_Size() int {
	return xxx_messageInfo_UrlsInText.Size(m)
}
func (m *UrlsInText) XXX_DiscardUnknown() {
	xxx_messageInfo_UrlsInText.DiscardUnknown(m)
}

var xxx_messageInfo_UrlsInText proto.InternalMessageInfo

func (m *UrlsInText) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UrlsInText) GetOriginalUrl() string {
	if m != nil {
		return m.OriginalUrl
	}
	return ""
}

func (m *UrlsInText) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Video struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Image                *Picture `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Duration             int64    `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Width                float64  `protobuf:"fixed64,4,opt,name=width,proto3" json:"width,omitempty"`
	Height               float64  `protobuf:"fixed64,5,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Video) Reset()         { *m = Video{} }
func (m *Video) String() string { return proto.CompactTextString(m) }
func (*Video) ProtoMessage()    {}
func (*Video) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{9}
}

func (m *Video) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Video.Unmarshal(m, b)
}
func (m *Video) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Video.Marshal(b, m, deterministic)
}
func (m *Video) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Video.Merge(m, src)
}
func (m *Video) XXX_Size() int {
	return xxx_messageInfo_Video.Size(m)
}
func (m *Video) XXX_DiscardUnknown() {
	xxx_messageInfo_Video.DiscardUnknown(m)
}

var xxx_messageInfo_Video proto.InternalMessageInfo

func (m *Video) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Video) GetImage() *Picture {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Video) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Video) GetWidth() float64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Video) GetHeight() float64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Audio struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Image                *Picture `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Audio) Reset()         { *m = Audio{} }
func (m *Audio) String() string { return proto.CompactTextString(m) }
func (*Audio) ProtoMessage()    {}
func (*Audio) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{10}
}

func (m *Audio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Audio.Unmarshal(m, b)
}
func (m *Audio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Audio.Marshal(b, m, deterministic)
}
func (m *Audio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Audio.Merge(m, src)
}
func (m *Audio) XXX_Size() int {
	return xxx_messageInfo_Audio.Size(m)
}
func (m *Audio) XXX_DiscardUnknown() {
	xxx_messageInfo_Audio.DiscardUnknown(m)
}

var xxx_messageInfo_Audio proto.InternalMessageInfo

func (m *Audio) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Audio) GetImage() *Picture {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Audio) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Audio) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

type OneMsgRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	UniversityId         int64    `protobuf:"varint,3,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OneMsgRequest) Reset()         { *m = OneMsgRequest{} }
func (m *OneMsgRequest) String() string { return proto.CompactTextString(m) }
func (*OneMsgRequest) ProtoMessage()    {}
func (*OneMsgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{11}
}

func (m *OneMsgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneMsgRequest.Unmarshal(m, b)
}
func (m *OneMsgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneMsgRequest.Marshal(b, m, deterministic)
}
func (m *OneMsgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneMsgRequest.Merge(m, src)
}
func (m *OneMsgRequest) XXX_Size() int {
	return xxx_messageInfo_OneMsgRequest.Size(m)
}
func (m *OneMsgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OneMsgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OneMsgRequest proto.InternalMessageInfo

func (m *OneMsgRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OneMsgRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OneMsgRequest) GetUniversityId() int64 {
	if m != nil {
		return m.UniversityId
	}
	return 0
}

type AllMsgListRequest struct {
	MsgType              int64    `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	OrderId              int64    `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	LoadMore             bool     `protobuf:"varint,3,opt,name=load_more,json=loadMore,proto3" json:"load_more,omitempty"`
	Uid                  string   `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid,omitempty"`
	UniversityId         int64    `protobuf:"varint,5,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllMsgListRequest) Reset()         { *m = AllMsgListRequest{} }
func (m *AllMsgListRequest) String() string { return proto.CompactTextString(m) }
func (*AllMsgListRequest) ProtoMessage()    {}
func (*AllMsgListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{12}
}

func (m *AllMsgListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllMsgListRequest.Unmarshal(m, b)
}
func (m *AllMsgListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllMsgListRequest.Marshal(b, m, deterministic)
}
func (m *AllMsgListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllMsgListRequest.Merge(m, src)
}
func (m *AllMsgListRequest) XXX_Size() int {
	return xxx_messageInfo_AllMsgListRequest.Size(m)
}
func (m *AllMsgListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllMsgListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllMsgListRequest proto.InternalMessageInfo

func (m *AllMsgListRequest) GetMsgType() int64 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *AllMsgListRequest) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *AllMsgListRequest) GetLoadMore() bool {
	if m != nil {
		return m.LoadMore
	}
	return false
}

func (m *AllMsgListRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AllMsgListRequest) GetUniversityId() int64 {
	if m != nil {
		return m.UniversityId
	}
	return 0
}

type UserMsgListRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	OrderId              int64    `protobuf:"varint,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
	MsgType              int64    `protobuf:"varint,3,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	UniversityId         int64    `protobuf:"varint,4,opt,name=universityId,proto3" json:"universityId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMsgListRequest) Reset()         { *m = UserMsgListRequest{} }
func (m *UserMsgListRequest) String() string { return proto.CompactTextString(m) }
func (*UserMsgListRequest) ProtoMessage()    {}
func (*UserMsgListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{13}
}

func (m *UserMsgListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMsgListRequest.Unmarshal(m, b)
}
func (m *UserMsgListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMsgListRequest.Marshal(b, m, deterministic)
}
func (m *UserMsgListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMsgListRequest.Merge(m, src)
}
func (m *UserMsgListRequest) XXX_Size() int {
	return xxx_messageInfo_UserMsgListRequest.Size(m)
}
func (m *UserMsgListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMsgListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserMsgListRequest proto.InternalMessageInfo

func (m *UserMsgListRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserMsgListRequest) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *UserMsgListRequest) GetMsgType() int64 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *UserMsgListRequest) GetUniversityId() int64 {
	if m != nil {
		return m.UniversityId
	}
	return 0
}

type HomeMsgListResponse struct {
	PublishMsgResponseList []*PublishMsgListResponse `protobuf:"bytes,1,rep,name=publishMsgResponseList,proto3" json:"publishMsgResponseList,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                  `json:"-"`
	XXX_unrecognized       []byte                    `json:"-"`
	XXX_sizecache          int32                     `json:"-"`
}

func (m *HomeMsgListResponse) Reset()         { *m = HomeMsgListResponse{} }
func (m *HomeMsgListResponse) String() string { return proto.CompactTextString(m) }
func (*HomeMsgListResponse) ProtoMessage()    {}
func (*HomeMsgListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{14}
}

func (m *HomeMsgListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HomeMsgListResponse.Unmarshal(m, b)
}
func (m *HomeMsgListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HomeMsgListResponse.Marshal(b, m, deterministic)
}
func (m *HomeMsgListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HomeMsgListResponse.Merge(m, src)
}
func (m *HomeMsgListResponse) XXX_Size() int {
	return xxx_messageInfo_HomeMsgListResponse.Size(m)
}
func (m *HomeMsgListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HomeMsgListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HomeMsgListResponse proto.InternalMessageInfo

func (m *HomeMsgListResponse) GetPublishMsgResponseList() []*PublishMsgListResponse {
	if m != nil {
		return m.PublishMsgResponseList
	}
	return nil
}

type OtherMsgListResponse struct {
	PublishMsgResponseList []*PublishMsgResponse `protobuf:"bytes,1,rep,name=publishMsgResponseList,proto3" json:"publishMsgResponseList,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}              `json:"-"`
	XXX_unrecognized       []byte                `json:"-"`
	XXX_sizecache          int32                 `json:"-"`
}

func (m *OtherMsgListResponse) Reset()         { *m = OtherMsgListResponse{} }
func (m *OtherMsgListResponse) String() string { return proto.CompactTextString(m) }
func (*OtherMsgListResponse) ProtoMessage()    {}
func (*OtherMsgListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{15}
}

func (m *OtherMsgListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OtherMsgListResponse.Unmarshal(m, b)
}
func (m *OtherMsgListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OtherMsgListResponse.Marshal(b, m, deterministic)
}
func (m *OtherMsgListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OtherMsgListResponse.Merge(m, src)
}
func (m *OtherMsgListResponse) XXX_Size() int {
	return xxx_messageInfo_OtherMsgListResponse.Size(m)
}
func (m *OtherMsgListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OtherMsgListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OtherMsgListResponse proto.InternalMessageInfo

func (m *OtherMsgListResponse) GetPublishMsgResponseList() []*PublishMsgResponse {
	if m != nil {
		return m.PublishMsgResponseList
	}
	return nil
}

type PublishMsgListResponse struct {
	Type                 string              `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Item                 *PublishMsgResponse `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Id                   string              `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PublishMsgListResponse) Reset()         { *m = PublishMsgListResponse{} }
func (m *PublishMsgListResponse) String() string { return proto.CompactTextString(m) }
func (*PublishMsgListResponse) ProtoMessage()    {}
func (*PublishMsgListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{16}
}

func (m *PublishMsgListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishMsgListResponse.Unmarshal(m, b)
}
func (m *PublishMsgListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishMsgListResponse.Marshal(b, m, deterministic)
}
func (m *PublishMsgListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishMsgListResponse.Merge(m, src)
}
func (m *PublishMsgListResponse) XXX_Size() int {
	return xxx_messageInfo_PublishMsgListResponse.Size(m)
}
func (m *PublishMsgListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishMsgListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishMsgListResponse proto.InternalMessageInfo

func (m *PublishMsgListResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PublishMsgListResponse) GetItem() *PublishMsgResponse {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *PublishMsgListResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MsgCommentListRequest struct {
	MsgId                string   `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	OrderId              int64    `protobuf:"varint,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCommentListRequest) Reset()         { *m = MsgCommentListRequest{} }
func (m *MsgCommentListRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCommentListRequest) ProtoMessage()    {}
func (*MsgCommentListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{17}
}

func (m *MsgCommentListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCommentListRequest.Unmarshal(m, b)
}
func (m *MsgCommentListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCommentListRequest.Marshal(b, m, deterministic)
}
func (m *MsgCommentListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCommentListRequest.Merge(m, src)
}
func (m *MsgCommentListRequest) XXX_Size() int {
	return xxx_messageInfo_MsgCommentListRequest.Size(m)
}
func (m *MsgCommentListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCommentListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCommentListRequest proto.InternalMessageInfo

func (m *MsgCommentListRequest) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *MsgCommentListRequest) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

type MsgCommentListResponse struct {
	PublishMsgComments   []*PublishMsgComment `protobuf:"bytes,1,rep,name=publishMsgComments,proto3" json:"publishMsgComments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MsgCommentListResponse) Reset()         { *m = MsgCommentListResponse{} }
func (m *MsgCommentListResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCommentListResponse) ProtoMessage()    {}
func (*MsgCommentListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{18}
}

func (m *MsgCommentListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCommentListResponse.Unmarshal(m, b)
}
func (m *MsgCommentListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCommentListResponse.Marshal(b, m, deterministic)
}
func (m *MsgCommentListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCommentListResponse.Merge(m, src)
}
func (m *MsgCommentListResponse) XXX_Size() int {
	return xxx_messageInfo_MsgCommentListResponse.Size(m)
}
func (m *MsgCommentListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCommentListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCommentListResponse proto.InternalMessageInfo

func (m *MsgCommentListResponse) GetPublishMsgComments() []*PublishMsgComment {
	if m != nil {
		return m.PublishMsgComments
	}
	return nil
}

type Response struct {
	// 响应是否成功
	Success int64 `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 响应信息
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{19}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() int64 {
	if m != nil {
		return m.Success
	}
	return 0
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type UserOperateCountRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	MsgId                string   `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Type                 int64    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserOperateCountRequest) Reset()         { *m = UserOperateCountRequest{} }
func (m *UserOperateCountRequest) String() string { return proto.CompactTextString(m) }
func (*UserOperateCountRequest) ProtoMessage()    {}
func (*UserOperateCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{20}
}

func (m *UserOperateCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserOperateCountRequest.Unmarshal(m, b)
}
func (m *UserOperateCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserOperateCountRequest.Marshal(b, m, deterministic)
}
func (m *UserOperateCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserOperateCountRequest.Merge(m, src)
}
func (m *UserOperateCountRequest) XXX_Size() int {
	return xxx_messageInfo_UserOperateCountRequest.Size(m)
}
func (m *UserOperateCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserOperateCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserOperateCountRequest proto.InternalMessageInfo

func (m *UserOperateCountRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserOperateCountRequest) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *UserOperateCountRequest) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

type UserOperateCountResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserOperateCountResponse) Reset()         { *m = UserOperateCountResponse{} }
func (m *UserOperateCountResponse) String() string { return proto.CompactTextString(m) }
func (*UserOperateCountResponse) ProtoMessage()    {}
func (*UserOperateCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{21}
}

func (m *UserOperateCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserOperateCountResponse.Unmarshal(m, b)
}
func (m *UserOperateCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserOperateCountResponse.Marshal(b, m, deterministic)
}
func (m *UserOperateCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserOperateCountResponse.Merge(m, src)
}
func (m *UserOperateCountResponse) XXX_Size() int {
	return xxx_messageInfo_UserOperateCountResponse.Size(m)
}
func (m *UserOperateCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserOperateCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserOperateCountResponse proto.InternalMessageInfo

func (m *UserOperateCountResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type UserOperateRecodeListRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Type                 int64    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserOperateRecodeListRequest) Reset()         { *m = UserOperateRecodeListRequest{} }
func (m *UserOperateRecodeListRequest) String() string { return proto.CompactTextString(m) }
func (*UserOperateRecodeListRequest) ProtoMessage()    {}
func (*UserOperateRecodeListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{22}
}

func (m *UserOperateRecodeListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserOperateRecodeListRequest.Unmarshal(m, b)
}
func (m *UserOperateRecodeListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserOperateRecodeListRequest.Marshal(b, m, deterministic)
}
func (m *UserOperateRecodeListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserOperateRecodeListRequest.Merge(m, src)
}
func (m *UserOperateRecodeListRequest) XXX_Size() int {
	return xxx_messageInfo_UserOperateRecodeListRequest.Size(m)
}
func (m *UserOperateRecodeListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserOperateRecodeListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserOperateRecodeListRequest proto.InternalMessageInfo

func (m *UserOperateRecodeListRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserOperateRecodeListRequest) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

type UserOperateRecodeListResponse struct {
	PublishMsg           []*PublishMsg `protobuf:"bytes,1,rep,name=publishMsg,proto3" json:"publishMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UserOperateRecodeListResponse) Reset()         { *m = UserOperateRecodeListResponse{} }
func (m *UserOperateRecodeListResponse) String() string { return proto.CompactTextString(m) }
func (*UserOperateRecodeListResponse) ProtoMessage()    {}
func (*UserOperateRecodeListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{23}
}

func (m *UserOperateRecodeListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserOperateRecodeListResponse.Unmarshal(m, b)
}
func (m *UserOperateRecodeListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserOperateRecodeListResponse.Marshal(b, m, deterministic)
}
func (m *UserOperateRecodeListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserOperateRecodeListResponse.Merge(m, src)
}
func (m *UserOperateRecodeListResponse) XXX_Size() int {
	return xxx_messageInfo_UserOperateRecodeListResponse.Size(m)
}
func (m *UserOperateRecodeListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserOperateRecodeListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserOperateRecodeListResponse proto.InternalMessageInfo

func (m *UserOperateRecodeListResponse) GetPublishMsg() []*PublishMsg {
	if m != nil {
		return m.PublishMsg
	}
	return nil
}

type DeleteMsgRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMsgRequest) Reset()         { *m = DeleteMsgRequest{} }
func (m *DeleteMsgRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMsgRequest) ProtoMessage()    {}
func (*DeleteMsgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{24}
}

func (m *DeleteMsgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMsgRequest.Unmarshal(m, b)
}
func (m *DeleteMsgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMsgRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMsgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMsgRequest.Merge(m, src)
}
func (m *DeleteMsgRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMsgRequest.Size(m)
}
func (m *DeleteMsgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMsgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMsgRequest proto.InternalMessageInfo

func (m *DeleteMsgRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *DeleteMsgRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteMsgCommentRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	MsgId                string   `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMsgCommentRequest) Reset()         { *m = DeleteMsgCommentRequest{} }
func (m *DeleteMsgCommentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMsgCommentRequest) ProtoMessage()    {}
func (*DeleteMsgCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{25}
}

func (m *DeleteMsgCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMsgCommentRequest.Unmarshal(m, b)
}
func (m *DeleteMsgCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMsgCommentRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMsgCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMsgCommentRequest.Merge(m, src)
}
func (m *DeleteMsgCommentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMsgCommentRequest.Size(m)
}
func (m *DeleteMsgCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMsgCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMsgCommentRequest proto.InternalMessageInfo

func (m *DeleteMsgCommentRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *DeleteMsgCommentRequest) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *DeleteMsgCommentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// 动态里的用户基本信息
type EsUserInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	ScreenName           string   `protobuf:"bytes,3,opt,name=screenName,proto3" json:"screenName,omitempty"`
	Bio                  string   `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	IsVerified           bool     `protobuf:"varint,5,opt,name=isVerified,proto3" json:"isVerified,omitempty"`
	VerifyMessage        string   `protobuf:"bytes,6,opt,name=verifyMessage,proto3" json:"verifyMessage,omitempty"`
	Zodiac               string   `protobuf:"bytes,7,opt,name=zodiac,proto3" json:"zodiac,omitempty"`
	AvatarImage          *Avatar  `protobuf:"bytes,8,opt,name=avatarImage,proto3" json:"avatarImage,omitempty"`
	UniversityId         int64    `protobuf:"varint,9,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EsUserInfo) Reset()         { *m = EsUserInfo{} }
func (m *EsUserInfo) String() string { return proto.CompactTextString(m) }
func (*EsUserInfo) ProtoMessage()    {}
func (*EsUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{26}
}

func (m *EsUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EsUserInfo.Unmarshal(m, b)
}
func (m *EsUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EsUserInfo.Marshal(b, m, deterministic)
}
func (m *EsUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EsUserInfo.Merge(m, src)
}
func (m *EsUserInfo) XXX_Size() int {
	return xxx_messageInfo_EsUserInfo.Size(m)
}
func (m *EsUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EsUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EsUserInfo proto.InternalMessageInfo

func (m *EsUserInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EsUserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *EsUserInfo) GetScreenName() string {
	if m != nil {
		return m.ScreenName
	}
	return ""
}

func (m *EsUserInfo) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *EsUserInfo) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

func (m *EsUserInfo) GetVerifyMessage() string {
	if m != nil {
		return m.VerifyMessage
	}
	return ""
}

func (m *EsUserInfo) GetZodiac() string {
	if m != nil {
		return m.Zodiac
	}
	return ""
}

func (m *EsUserInfo) GetAvatarImage() *Avatar {
	if m != nil {
		return m.AvatarImage
	}
	return nil
}

func (m *EsUserInfo) GetUniversityId() int64 {
	if m != nil {
		return m.UniversityId
	}
	return 0
}

type Avatar struct {
	ThumbnailUrl         string   `protobuf:"bytes,1,opt,name=thumbnailUrl,proto3" json:"thumbnailUrl,omitempty"`
	SmallPicUrl          string   `protobuf:"bytes,2,opt,name=smallPicUrl,proto3" json:"smallPicUrl,omitempty"`
	PicUrl               string   `protobuf:"bytes,3,opt,name=picUrl,proto3" json:"picUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Avatar) Reset()         { *m = Avatar{} }
func (m *Avatar) String() string { return proto.CompactTextString(m) }
func (*Avatar) ProtoMessage()    {}
func (*Avatar) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0be33c920f5eaf9, []int{27}
}

func (m *Avatar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Avatar.Unmarshal(m, b)
}
func (m *Avatar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Avatar.Marshal(b, m, deterministic)
}
func (m *Avatar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Avatar.Merge(m, src)
}
func (m *Avatar) XXX_Size() int {
	return xxx_messageInfo_Avatar.Size(m)
}
func (m *Avatar) XXX_DiscardUnknown() {
	xxx_messageInfo_Avatar.DiscardUnknown(m)
}

var xxx_messageInfo_Avatar proto.InternalMessageInfo

func (m *Avatar) GetThumbnailUrl() string {
	if m != nil {
		return m.ThumbnailUrl
	}
	return ""
}

func (m *Avatar) GetSmallPicUrl() string {
	if m != nil {
		return m.SmallPicUrl
	}
	return ""
}

func (m *Avatar) GetPicUrl() string {
	if m != nil {
		return m.PicUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*PublishMsg)(nil), "university_circles.srv.home.PublishMsg")
	proto.RegisterType((*PublishMsgResponse)(nil), "university_circles.srv.home.PublishMsgResponse")
	proto.RegisterType((*PublishMsgComment)(nil), "university_circles.srv.home.PublishMsgComment")
	proto.RegisterType((*PictureReq)(nil), "university_circles.srv.home.PictureReq")
	proto.RegisterType((*Picture)(nil), "university_circles.srv.home.Picture")
	proto.RegisterType((*Poi)(nil), "university_circles.srv.home.Poi")
	proto.RegisterType((*Location)(nil), "university_circles.srv.home.Location")
	proto.RegisterType((*LinkInfo)(nil), "university_circles.srv.home.LinkInfo")
	proto.RegisterType((*UrlsInText)(nil), "university_circles.srv.home.UrlsInText")
	proto.RegisterType((*Video)(nil), "university_circles.srv.home.Video")
	proto.RegisterType((*Audio)(nil), "university_circles.srv.home.Audio")
	proto.RegisterType((*OneMsgRequest)(nil), "university_circles.srv.home.OneMsgRequest")
	proto.RegisterType((*AllMsgListRequest)(nil), "university_circles.srv.home.AllMsgListRequest")
	proto.RegisterType((*UserMsgListRequest)(nil), "university_circles.srv.home.UserMsgListRequest")
	proto.RegisterType((*HomeMsgListResponse)(nil), "university_circles.srv.home.HomeMsgListResponse")
	proto.RegisterType((*OtherMsgListResponse)(nil), "university_circles.srv.home.OtherMsgListResponse")
	proto.RegisterType((*PublishMsgListResponse)(nil), "university_circles.srv.home.PublishMsgListResponse")
	proto.RegisterType((*MsgCommentListRequest)(nil), "university_circles.srv.home.MsgCommentListRequest")
	proto.RegisterType((*MsgCommentListResponse)(nil), "university_circles.srv.home.MsgCommentListResponse")
	proto.RegisterType((*Response)(nil), "university_circles.srv.home.Response")
	proto.RegisterType((*UserOperateCountRequest)(nil), "university_circles.srv.home.UserOperateCountRequest")
	proto.RegisterType((*UserOperateCountResponse)(nil), "university_circles.srv.home.UserOperateCountResponse")
	proto.RegisterType((*UserOperateRecodeListRequest)(nil), "university_circles.srv.home.UserOperateRecodeListRequest")
	proto.RegisterType((*UserOperateRecodeListResponse)(nil), "university_circles.srv.home.UserOperateRecodeListResponse")
	proto.RegisterType((*DeleteMsgRequest)(nil), "university_circles.srv.home.DeleteMsgRequest")
	proto.RegisterType((*DeleteMsgCommentRequest)(nil), "university_circles.srv.home.DeleteMsgCommentRequest")
	proto.RegisterType((*EsUserInfo)(nil), "university_circles.srv.home.EsUserInfo")
	proto.RegisterType((*Avatar)(nil), "university_circles.srv.home.Avatar")
}

func init() { proto.RegisterFile("home/home.proto", fileDescriptor_a0be33c920f5eaf9) }

var fileDescriptor_a0be33c920f5eaf9 = []byte{
	// 1681 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xcb, 0x6e, 0xdb, 0xcc,
	0x15, 0x0e, 0x75, 0xb3, 0x74, 0x64, 0x3b, 0xf6, 0xfc, 0xf9, 0x1d, 0xfe, 0x8e, 0x5b, 0x08, 0x4c,
	0x8a, 0x18, 0x01, 0xea, 0xa4, 0x4e, 0x5a, 0xf4, 0xb2, 0xa9, 0xe1, 0x24, 0x8e, 0x80, 0xb8, 0x31,
	0x98, 0xc4, 0xcb, 0x1a, 0x34, 0x39, 0x96, 0xa6, 0x26, 0x39, 0x0a, 0x67, 0xa8, 0xd8, 0x5d, 0x34,
	0x68, 0x81, 0xa2, 0xab, 0x3e, 0x42, 0x17, 0x7d, 0x82, 0x6e, 0xda, 0x67, 0xe8, 0xb2, 0x4f, 0xd0,
	0x6d, 0x1f, 0xa0, 0x4f, 0x50, 0xcc, 0x85, 0xe4, 0x50, 0x17, 0x5a, 0x32, 0xd2, 0x8d, 0xc0, 0x73,
	0x38, 0xe7, 0xfe, 0xcd, 0x39, 0x47, 0x84, 0xbb, 0x43, 0x1a, 0xe1, 0xa7, 0xe2, 0x67, 0x6f, 0x94,
	0x50, 0x4e, 0xd1, 0x83, 0x34, 0x26, 0x63, 0x9c, 0x30, 0xc2, 0xaf, 0xcf, 0x7c, 0x92, 0xf8, 0x21,
	0x66, 0x7b, 0x2c, 0x19, 0xef, 0x89, 0x23, 0xce, 0xbf, 0x6b, 0x00, 0x27, 0xe9, 0x79, 0x48, 0xd8,
	0xf0, 0x98, 0x0d, 0xd0, 0x06, 0xd4, 0x53, 0x12, 0xd8, 0x56, 0xcf, 0xda, 0xed, 0xb8, 0xe2, 0x11,
	0xd9, 0xb0, 0xe2, 0xd3, 0x98, 0xe3, 0x98, 0xdb, 0x35, 0xc9, 0xcd, 0x48, 0x74, 0x08, 0xed, 0x11,
	0xf1, 0x79, 0x9a, 0x60, 0x66, 0xd7, 0x7b, 0xf5, 0xdd, 0xee, 0xfe, 0xe3, 0xbd, 0x0a, 0x53, 0x7b,
	0x27, 0xea, 0xb0, 0x8b, 0x3f, 0xb9, 0xb9, 0x20, 0xda, 0x87, 0xfa, 0x88, 0x12, 0xbb, 0xd1, 0xb3,
	0x76, 0xbb, 0xfb, 0xbd, 0x6a, 0x79, 0x4a, 0x5c, 0x71, 0x18, 0x21, 0x68, 0xf0, 0xeb, 0x11, 0xb6,
	0x9b, 0xd2, 0x1f, 0xf9, 0x8c, 0xbe, 0x83, 0x76, 0xc4, 0x06, 0x67, 0x92, 0xdf, 0xea, 0x59, 0xbb,
	0x75, 0x77, 0x25, 0x62, 0x83, 0x0f, 0xe2, 0xd5, 0x01, 0xb4, 0xdf, 0x92, 0xf8, 0xb2, 0x1f, 0x5f,
	0x50, 0x7b, 0x45, 0xda, 0xf9, 0x41, 0xa5, 0x9d, 0xec, 0xb0, 0x9b, 0x8b, 0xa1, 0x9f, 0x42, 0x73,
	0x4c, 0x02, 0x4c, 0xed, 0xb6, 0x94, 0x77, 0x2a, 0xe5, 0x4f, 0xc5, 0x49, 0x57, 0x09, 0x38, 0xff,
	0x6a, 0x02, 0x2a, 0xf2, 0xeb, 0x62, 0x36, 0xa2, 0x31, 0xc3, 0x68, 0x1d, 0x6a, 0x79, 0x9a, 0x6b,
	0x24, 0x28, 0xb9, 0x5f, 0x2b, 0xbb, 0x6f, 0x14, 0xa0, 0x5e, 0x2e, 0xc0, 0x2f, 0x8d, 0x02, 0x34,
	0x64, 0x01, 0x1e, 0x2d, 0x54, 0x80, 0xa9, 0xec, 0x37, 0x6f, 0x93, 0xfd, 0x96, 0x91, 0xfd, 0x2d,
	0x68, 0x31, 0xee, 0xf1, 0x94, 0xc9, 0x04, 0x77, 0x5c, 0x4d, 0x21, 0x07, 0x56, 0x7d, 0x1a, 0x45,
	0x38, 0xe6, 0x87, 0x34, 0x8d, 0xb9, 0x4c, 0x5f, 0xdd, 0x2d, 0xf1, 0xd0, 0xf7, 0x01, 0xd8, 0xd0,
	0x4b, 0xb0, 0x3a, 0xd1, 0x91, 0x27, 0x0c, 0x0e, 0xda, 0x81, 0x4e, 0x48, 0x2e, 0xf5, 0x6b, 0x90,
	0xaf, 0x0b, 0x46, 0xa9, 0xb8, 0xdd, 0xdb, 0x15, 0x77, 0x07, 0x3a, 0x7e, 0x82, 0x3d, 0x8e, 0x83,
	0x03, 0x6e, 0xaf, 0x4a, 0xff, 0x0b, 0x06, 0xfa, 0x05, 0x34, 0x52, 0x86, 0x13, 0x7b, 0x4d, 0x2a,
	0xaf, 0x46, 0xf8, 0x2b, 0xf6, 0x91, 0xe1, 0x44, 0xaa, 0x97, 0x42, 0x68, 0x0f, 0x10, 0x61, 0x87,
	0x2a, 0xda, 0xd7, 0x34, 0x39, 0x27, 0x41, 0x80, 0x63, 0x7b, 0xbd, 0x67, 0xed, 0xb6, 0xdd, 0x19,
	0x6f, 0xd0, 0x3d, 0x68, 0x8a, 0xd0, 0x02, 0xfb, 0xae, 0x3c, 0xa2, 0x08, 0xe9, 0x20, 0x0d, 0x43,
	0xec, 0x73, 0x1c, 0xd8, 0x1b, 0xf2, 0x4d, 0xc1, 0x10, 0xf8, 0xa0, 0x49, 0x80, 0x93, 0x7e, 0x60,
	0x6f, 0x2a, 0xe4, 0x68, 0xb2, 0x40, 0x2d, 0x5a, 0x12, 0xb5, 0x68, 0x1b, 0xda, 0x84, 0xbd, 0xa6,
	0x61, 0x48, 0x3f, 0xdb, 0xdf, 0x48, 0x83, 0x39, 0xed, 0xfc, 0xb3, 0x01, 0x9b, 0x05, 0xa2, 0x75,
	0x08, 0x53, 0x80, 0xde, 0x86, 0x36, 0xf7, 0x92, 0x01, 0xe6, 0xfd, 0x40, 0xf7, 0x8d, 0x9c, 0xfe,
	0xbf, 0x22, 0x3a, 0xcf, 0x60, 0xd3, 0xcc, 0xe0, 0x32, 0x98, 0x15, 0x1a, 0xf0, 0x18, 0x87, 0x1a,
	0xac, 0x8a, 0x10, 0x28, 0x4d, 0xf0, 0x28, 0xbc, 0x2e, 0xa1, 0xb4, 0xe0, 0xdc, 0x80, 0xd2, 0x53,
	0x58, 0x97, 0x67, 0x3f, 0x50, 0x9d, 0x2f, 0x8d, 0xd5, 0xbd, 0xea, 0xe8, 0x26, 0xb3, 0xec, 0x4e,
	0x68, 0x41, 0x47, 0x00, 0x69, 0x12, 0xb2, 0x7e, 0xfc, 0x01, 0x5f, 0x09, 0xec, 0xde, 0xdc, 0x84,
	0x3f, 0xe6, 0xc7, 0x5d, 0x43, 0xb4, 0x7c, 0x07, 0xd6, 0xe6, 0xdd, 0x81, 0xf5, 0xdb, 0xdc, 0x01,
	0x03, 0x9f, 0x77, 0x4b, 0xf8, 0x74, 0x42, 0x80, 0x62, 0x26, 0x88, 0x73, 0x24, 0xf2, 0x06, 0xb8,
	0x9f, 0xc1, 0x28, 0x23, 0x45, 0x45, 0x3e, 0x93, 0x80, 0x0f, 0x75, 0x67, 0x54, 0x84, 0xa8, 0xdf,
	0x10, 0x93, 0xc1, 0x50, 0x81, 0xa8, 0xee, 0x6a, 0x4a, 0xf0, 0x2f, 0x68, 0x12, 0x79, 0x5c, 0x0e,
	0x95, 0x8e, 0xab, 0x29, 0xe7, 0x6f, 0x16, 0xac, 0x68, 0x73, 0xa2, 0x2f, 0xf1, 0x61, 0x1a, 0x9d,
	0xc7, 0x1e, 0x09, 0x3f, 0x26, 0xa1, 0x36, 0x58, 0xe2, 0x89, 0x33, 0x11, 0x09, 0x82, 0x10, 0x9f,
	0x10, 0x5f, 0x9c, 0x51, 0x28, 0x2e, 0xf1, 0x84, 0xad, 0x91, 0x7a, 0xab, 0x80, 0xac, 0xa9, 0x79,
	0x3e, 0x14, 0x91, 0x34, 0x67, 0x47, 0xd2, 0x32, 0x23, 0x71, 0xfe, 0x6b, 0x41, 0xfd, 0x84, 0x12,
	0xd1, 0xe3, 0x42, 0xea, 0x7b, 0x9c, 0xd0, 0xd8, 0xb6, 0x64, 0x8d, 0x6f, 0xe8, 0x71, 0xfa, 0xb0,
	0x9b, 0x8b, 0xa1, 0x1e, 0x74, 0x7d, 0x81, 0xc4, 0xe4, 0x3a, 0xf6, 0x22, 0xac, 0x63, 0x31, 0x59,
	0xc2, 0xb5, 0x11, 0x25, 0xfd, 0x40, 0x47, 0xa2, 0x08, 0xf4, 0x04, 0x36, 0x94, 0xeb, 0x02, 0x08,
	0x41, 0x90, 0x60, 0xc6, 0x74, 0x48, 0x53, 0x7c, 0x71, 0xe5, 0x7d, 0xc2, 0x95, 0x01, 0x35, 0x9a,
	0x73, 0x5a, 0x6a, 0x97, 0x2f, 0x5a, 0x5a, 0xbb, 0xe4, 0x22, 0x68, 0x48, 0xa6, 0xba, 0x80, 0xf2,
	0xd9, 0xd9, 0x81, 0x76, 0xe6, 0xbf, 0xd8, 0x46, 0x42, 0xea, 0xcb, 0xea, 0x58, 0xae, 0x78, 0x74,
	0xfe, 0x63, 0x15, 0xfd, 0x5e, 0x28, 0xe5, 0x84, 0x87, 0x58, 0x97, 0x4f, 0x11, 0xe2, 0xa6, 0xea,
	0x6e, 0x50, 0x54, 0xcd, 0xe0, 0x08, 0x9c, 0x85, 0x24, 0xbe, 0x2c, 0x8a, 0x96, 0x91, 0xb2, 0x23,
	0xd0, 0x34, 0xf1, 0x71, 0x56, 0x35, 0x45, 0x89, 0x3e, 0xea, 0xa5, 0x01, 0xa1, 0x7a, 0x4e, 0x56,
	0xf7, 0xd1, 0x03, 0x71, 0xd2, 0x55, 0x02, 0x45, 0x07, 0x6e, 0x2d, 0xbb, 0x37, 0x9c, 0x02, 0x14,
	0x57, 0x75, 0x4e, 0xa4, 0x3d, 0xe8, 0xd2, 0x84, 0x0c, 0x48, 0xec, 0x85, 0x45, 0xa8, 0x26, 0x4b,
	0xae, 0x73, 0x79, 0x9c, 0xe2, 0xd1, 0xf9, 0xab, 0x05, 0x4d, 0x69, 0x28, 0xef, 0x89, 0x96, 0xd1,
	0x13, 0x7f, 0x0e, 0x4d, 0x79, 0xe9, 0xa4, 0xae, 0x45, 0x9b, 0xaf, 0x12, 0x11, 0xe5, 0x0f, 0xd2,
	0x44, 0xa1, 0x54, 0xdd, 0xc8, 0x9c, 0x2e, 0x70, 0xdf, 0x90, 0xa5, 0x9c, 0xc2, 0x7d, 0x53, 0xb2,
	0x33, 0xdc, 0xff, 0xd1, 0x82, 0xa6, 0x4c, 0xe3, 0x57, 0xf7, 0x31, 0xcf, 0x63, 0xdd, 0xcc, 0xe3,
	0x16, 0xb4, 0xbc, 0x94, 0x0f, 0x69, 0x92, 0xd5, 0x5d, 0x51, 0xce, 0x29, 0xac, 0xbd, 0x8b, 0xb1,
	0x5c, 0xdb, 0x3e, 0xa5, 0x98, 0x4d, 0x0f, 0x39, 0xbd, 0x2d, 0xd7, 0x8a, 0x6d, 0xf9, 0x21, 0xac,
	0x19, 0xee, 0x90, 0x40, 0x67, 0x62, 0xb5, 0x60, 0xf6, 0x03, 0xe7, 0x2f, 0x16, 0x6c, 0x1e, 0x84,
	0xe1, 0x31, 0x1b, 0xbc, 0x25, 0x8c, 0x67, 0xca, 0xcd, 0x15, 0xd0, 0x2a, 0xaf, 0x80, 0xdf, 0x41,
	0x5b, 0xf6, 0xcc, 0x33, 0x6d, 0xcc, 0x98, 0xf1, 0x0f, 0xa0, 0x13, 0x52, 0x2f, 0x38, 0x8b, 0x68,
	0xa2, 0xa2, 0x6a, 0x8b, 0x5b, 0xef, 0x05, 0xc7, 0x34, 0xc1, 0x99, 0x7f, 0x8d, 0x0a, 0xff, 0x9a,
	0x33, 0xfc, 0xfb, 0x02, 0x48, 0xf4, 0xf0, 0x09, 0xff, 0x66, 0xfe, 0x35, 0xc8, 0x3a, 0xfb, 0x84,
	0x57, 0x66, 0x2c, 0xf5, 0x72, 0x2c, 0x0e, 0x94, 0x8c, 0x49, 0xe7, 0x26, 0x1d, 0xf8, 0x83, 0x05,
	0xdf, 0xbc, 0xa1, 0x11, 0xce, 0x3d, 0xd0, 0x5b, 0xf3, 0x25, 0x6c, 0x8d, 0xa6, 0x76, 0x69, 0x71,
	0x42, 0xb7, 0xc5, 0xe7, 0x0b, 0x8e, 0x53, 0x53, 0xa9, 0x3b, 0x47, 0xa5, 0xf3, 0x05, 0xee, 0xbd,
	0xe3, 0x43, 0x23, 0x0d, 0xda, 0x89, 0xc1, 0x0d, 0x4e, 0x3c, 0x5d, 0xd0, 0x89, 0x1b, 0x1d, 0xf8,
	0xbd, 0x05, 0x5b, 0xb3, 0x7d, 0x9e, 0x79, 0x2f, 0x0e, 0xa1, 0x41, 0x38, 0x8e, 0xf4, 0xb5, 0x58,
	0xda, 0x0b, 0x29, 0xac, 0x11, 0x5e, 0xcf, 0x10, 0xee, 0xbc, 0x81, 0x6f, 0x8b, 0xf5, 0xc3, 0x44,
	0xc3, 0xb7, 0xd0, 0x12, 0x15, 0xce, 0x01, 0xd1, 0x8c, 0xd8, 0xa0, 0x5f, 0x01, 0x09, 0xe7, 0x0a,
	0xb6, 0x26, 0x35, 0xe9, 0x60, 0x7e, 0x0d, 0x68, 0x34, 0xb9, 0xe9, 0x30, 0x9d, 0xcc, 0x65, 0x17,
	0xa4, 0x19, 0x9a, 0x9c, 0x9f, 0x40, 0x3b, 0xb7, 0x65, 0xc3, 0x0a, 0x4b, 0x7d, 0x5f, 0x8c, 0x31,
	0x7d, 0xc7, 0x34, 0x29, 0xe0, 0x1d, 0xb1, 0x41, 0x76, 0x97, 0x23, 0x36, 0x70, 0x4e, 0xe1, 0xbe,
	0xb8, 0x06, 0xef, 0x46, 0x38, 0xf1, 0xb8, 0x5a, 0xe4, 0xe6, 0xdf, 0x85, 0x22, 0x1f, 0x35, 0x33,
	0x1f, 0x59, 0xa1, 0xd4, 0x25, 0x90, 0xcf, 0xce, 0x33, 0xb0, 0xa7, 0xf5, 0x6a, 0xff, 0xee, 0x41,
	0x53, 0x0e, 0x65, 0xed, 0x9d, 0x22, 0x9c, 0x97, 0xb0, 0x63, 0x48, 0xb8, 0xd8, 0xa7, 0x01, 0xae,
	0xbe, 0x9a, 0x99, 0xdd, 0x9a, 0x61, 0x77, 0x08, 0xdf, 0x9b, 0xa3, 0x45, 0x1b, 0x3f, 0x02, 0x28,
	0xd2, 0xa7, 0x0b, 0xf0, 0x78, 0x51, 0x1c, 0x19, 0xa2, 0xce, 0x0b, 0xd8, 0x78, 0x89, 0x43, 0xcc,
	0xcd, 0xde, 0x39, 0xed, 0xa3, 0xc2, 0x5a, 0x2d, 0xc7, 0x9a, 0x0b, 0xf7, 0x73, 0xa9, 0xac, 0x9e,
	0xcb, 0xe6, 0x7b, 0x12, 0xbf, 0x7f, 0xaf, 0x01, 0x14, 0x1b, 0xe9, 0xac, 0x7f, 0x29, 0x62, 0x47,
	0x35, 0x76, 0xa2, 0x9c, 0x96, 0xff, 0x4b, 0xfd, 0x04, 0xe3, 0xf8, 0x57, 0xe2, 0xad, 0x52, 0x69,
	0x70, 0x84, 0x4f, 0xe7, 0x84, 0x66, 0xcd, 0xf5, 0x9c, 0x50, 0x21, 0x41, 0xd8, 0x29, 0x4e, 0xc8,
	0x05, 0xc9, 0xff, 0x80, 0x18, 0x1c, 0xf4, 0x08, 0xd6, 0xc6, 0xe2, 0xf9, 0xfa, 0x18, 0x33, 0x26,
	0x26, 0x98, 0x5a, 0x86, 0xca, 0x4c, 0x31, 0x8d, 0x7e, 0x4b, 0x03, 0xe2, 0xf9, 0xd9, 0xff, 0x12,
	0x45, 0xa1, 0x57, 0xd0, 0xf5, 0xc6, 0x1e, 0xf7, 0x92, 0xbe, 0x9c, 0x7e, 0xea, 0x4b, 0xc4, 0xc3,
	0xea, 0x5d, 0x44, 0x9e, 0x77, 0x4d, 0xb9, 0xe9, 0x09, 0xd0, 0x99, 0xd1, 0x80, 0x2f, 0xa0, 0xa5,
	0x64, 0x17, 0xda, 0x94, 0x7b, 0xd0, 0x65, 0x91, 0x17, 0x86, 0xa5, 0x45, 0xd9, 0x64, 0xcd, 0xdb,
	0x93, 0xf7, 0xff, 0x01, 0xd0, 0x15, 0x8d, 0xfe, 0x3d, 0x4e, 0xc6, 0xc4, 0xc7, 0xe8, 0x1c, 0xd6,
	0xdf, 0x7b, 0x63, 0x6c, 0x7c, 0x90, 0x5a, 0x14, 0x7f, 0xdb, 0xd5, 0x2b, 0x71, 0x86, 0x71, 0xe7,
	0x0e, 0xfa, 0x4d, 0x06, 0x4e, 0xc3, 0xca, 0x0f, 0x2b, 0x85, 0x27, 0xb1, 0xbc, 0xb8, 0x2d, 0x0e,
	0xeb, 0x47, 0x98, 0x1b, 0xa3, 0x0c, 0x55, 0x37, 0xb4, 0xa9, 0xad, 0x60, 0xfb, 0x59, 0xe5, 0xf9,
	0x19, 0x43, 0xd2, 0xb9, 0x83, 0xc6, 0xd2, 0xaa, 0x31, 0xc2, 0x51, 0xf5, 0x34, 0x98, 0x1e, 0xf6,
	0xdb, 0x3f, 0xaa, 0x14, 0x98, 0x35, 0x17, 0x9d, 0x3b, 0x88, 0xc2, 0xea, 0x11, 0xe6, 0xc7, 0x6c,
	0xf0, 0x12, 0x73, 0x8f, 0x84, 0xe8, 0x49, 0xb5, 0x12, 0x73, 0xb5, 0xba, 0x9d, 0x41, 0xa2, 0xe0,
	0x62, 0x7c, 0x86, 0x58, 0x72, 0x5e, 0x2c, 0x5e, 0xc9, 0xdf, 0xc1, 0xa6, 0x8a, 0xcd, 0x98, 0x60,
	0x68, 0xbf, 0x52, 0x7a, 0xe6, 0xe0, 0xdc, 0x7e, 0xbe, 0x94, 0x4c, 0x6e, 0xff, 0x2a, 0x6b, 0x8e,
	0xd3, 0x9f, 0x5e, 0x5e, 0x2c, 0x06, 0xde, 0x72, 0x4b, 0x5d, 0x3c, 0xf2, 0x2b, 0xb8, 0x2f, 0x92,
	0x6c, 0x8c, 0x0e, 0xa9, 0x2c, 0xbd, 0xd1, 0xf2, 0x9c, 0xe1, 0xb9, 0xb8, 0xe5, 0x3f, 0x59, 0xb0,
	0xa5, 0x81, 0xfc, 0x75, 0x2c, 0xff, 0x78, 0x49, 0xa9, 0xdc, 0x93, 0x3f, 0x5b, 0xf0, 0x60, 0xca,
	0x93, 0x62, 0x82, 0xa2, 0x9f, 0x2d, 0xaa, 0x78, 0x6a, 0x76, 0xdf, 0x0a, 0xf8, 0xe7, 0x2d, 0xf9,
	0x65, 0xff, 0xf9, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x44, 0xc4, 0x77, 0x06, 0xec, 0x17, 0x00,
	0x00,
}
