// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: common/common.proto

package university_circles_srv_common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CommonService service

type CommonService interface {
	// 通过反馈接口  1、反馈  2、举报首页消息 3、举报商品
	Report(ctx context.Context, in *ReportReq, opts ...client.CallOption) (*Response, error)
}

type commonService struct {
	c    client.Client
	name string
}

func NewCommonService(name string, c client.Client) CommonService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "university_circles.srv.common"
	}
	return &commonService{
		c:    c,
		name: name,
	}
}

func (c *commonService) Report(ctx context.Context, in *ReportReq, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "CommonService.Report", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CommonService service

type CommonServiceHandler interface {
	// 通过反馈接口  1、反馈  2、举报首页消息 3、举报商品
	Report(context.Context, *ReportReq, *Response) error
}

func RegisterCommonServiceHandler(s server.Server, hdlr CommonServiceHandler, opts ...server.HandlerOption) error {
	type commonService interface {
		Report(ctx context.Context, in *ReportReq, out *Response) error
	}
	type CommonService struct {
		commonService
	}
	h := &commonServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&CommonService{h}, opts...))
}

type commonServiceHandler struct {
	CommonServiceHandler
}

func (h *commonServiceHandler) Report(ctx context.Context, in *ReportReq, out *Response) error {
	return h.CommonServiceHandler.Report(ctx, in, out)
}
