env = "development"

[default_redis]
    [default_redis.development]
    host="127.0.0.1"
    port="6379"
    password="jKCrqE#b3XINybCyGp38H&z4eHbH#rby"
    maxIdle=10
    maxOpen=1000
    connect_timeout=1
    read_timeout=3
    write_timeout=3
    idle_timeout=300

    [default_redis.production]
    hhost="127.0.0.1"
    port="6379"
    password="jKCrqE#b3XINybCyGp38H&z4eHbH#rby"
    maxIdle=100
    maxOpen=3000
    connect_timeout=1
    read_timeout=3
    write_timeout=3
    idle_timeout=300
