// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package im

var TableNames = struct {
	Blacklist         string
	Friend            string
	Group             string
	GroupMember       string
	UniversityStudent string
	UniversityTeacher string
}{
	Blacklist:         "blacklist",
	Friend:            "friend",
	Group:             "group",
	GroupMember:       "group_member",
	UniversityStudent: "university_student",
	UniversityTeacher: "university_teacher",
}
