// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package user

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// UniversityCollegeProfessionClass is an object representing the database table.
type UniversityCollegeProfessionClass struct {
	ID           int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	UniversityID int         `boil:"university_id" json:"university_id" toml:"university_id" yaml:"university_id"`
	CollegeID    int         `boil:"college_id" json:"college_id" toml:"college_id" yaml:"college_id"`
	ProfessionID int         `boil:"profession_id" json:"profession_id" toml:"profession_id" yaml:"profession_id"`
	Name         string      `boil:"name" json:"name" toml:"name" yaml:"name"`
	Status       null.Int8   `boil:"status" json:"status,omitempty" toml:"status" yaml:"status,omitempty"`
	Deleted      int8        `boil:"deleted" json:"deleted" toml:"deleted" yaml:"deleted"`
	Created      null.Time   `boil:"created" json:"created,omitempty" toml:"created" yaml:"created,omitempty"`
	CreatedUser  null.String `boil:"created_user" json:"created_user,omitempty" toml:"created_user" yaml:"created_user,omitempty"`
	Modified     null.Time   `boil:"modified" json:"modified,omitempty" toml:"modified" yaml:"modified,omitempty"`
	ModifiedUser null.String `boil:"modified_user" json:"modified_user,omitempty" toml:"modified_user" yaml:"modified_user,omitempty"`

	R *universityCollegeProfessionClassR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L universityCollegeProfessionClassL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UniversityCollegeProfessionClassColumns = struct {
	ID           string
	UniversityID string
	CollegeID    string
	ProfessionID string
	Name         string
	Status       string
	Deleted      string
	Created      string
	CreatedUser  string
	Modified     string
	ModifiedUser string
}{
	ID:           "id",
	UniversityID: "university_id",
	CollegeID:    "college_id",
	ProfessionID: "profession_id",
	Name:         "name",
	Status:       "status",
	Deleted:      "deleted",
	Created:      "created",
	CreatedUser:  "created_user",
	Modified:     "modified",
	ModifiedUser: "modified_user",
}

// Generated where

var UniversityCollegeProfessionClassWhere = struct {
	ID           whereHelperint
	UniversityID whereHelperint
	CollegeID    whereHelperint
	ProfessionID whereHelperint
	Name         whereHelperstring
	Status       whereHelpernull_Int8
	Deleted      whereHelperint8
	Created      whereHelpernull_Time
	CreatedUser  whereHelpernull_String
	Modified     whereHelpernull_Time
	ModifiedUser whereHelpernull_String
}{
	ID:           whereHelperint{field: "`university_college_profession_class`.`id`"},
	UniversityID: whereHelperint{field: "`university_college_profession_class`.`university_id`"},
	CollegeID:    whereHelperint{field: "`university_college_profession_class`.`college_id`"},
	ProfessionID: whereHelperint{field: "`university_college_profession_class`.`profession_id`"},
	Name:         whereHelperstring{field: "`university_college_profession_class`.`name`"},
	Status:       whereHelpernull_Int8{field: "`university_college_profession_class`.`status`"},
	Deleted:      whereHelperint8{field: "`university_college_profession_class`.`deleted`"},
	Created:      whereHelpernull_Time{field: "`university_college_profession_class`.`created`"},
	CreatedUser:  whereHelpernull_String{field: "`university_college_profession_class`.`created_user`"},
	Modified:     whereHelpernull_Time{field: "`university_college_profession_class`.`modified`"},
	ModifiedUser: whereHelpernull_String{field: "`university_college_profession_class`.`modified_user`"},
}

// UniversityCollegeProfessionClassRels is where relationship names are stored.
var UniversityCollegeProfessionClassRels = struct {
}{}

// universityCollegeProfessionClassR is where relationships are stored.
type universityCollegeProfessionClassR struct {
}

// NewStruct creates a new relationship struct
func (*universityCollegeProfessionClassR) NewStruct() *universityCollegeProfessionClassR {
	return &universityCollegeProfessionClassR{}
}

// universityCollegeProfessionClassL is where Load methods for each relationship are stored.
type universityCollegeProfessionClassL struct{}

var (
	universityCollegeProfessionClassAllColumns            = []string{"id", "university_id", "college_id", "profession_id", "name", "status", "deleted", "created", "created_user", "modified", "modified_user"}
	universityCollegeProfessionClassColumnsWithoutDefault = []string{"name", "created_user", "modified_user"}
	universityCollegeProfessionClassColumnsWithDefault    = []string{"id", "university_id", "college_id", "profession_id", "status", "deleted", "created", "modified"}
	universityCollegeProfessionClassPrimaryKeyColumns     = []string{"id"}
)

type (
	// UniversityCollegeProfessionClassSlice is an alias for a slice of pointers to UniversityCollegeProfessionClass.
	// This should generally be used opposed to []UniversityCollegeProfessionClass.
	UniversityCollegeProfessionClassSlice []*UniversityCollegeProfessionClass
	// UniversityCollegeProfessionClassHook is the signature for custom UniversityCollegeProfessionClass hook methods
	UniversityCollegeProfessionClassHook func(context.Context, boil.ContextExecutor, *UniversityCollegeProfessionClass) error

	universityCollegeProfessionClassQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	universityCollegeProfessionClassType                 = reflect.TypeOf(&UniversityCollegeProfessionClass{})
	universityCollegeProfessionClassMapping              = queries.MakeStructMapping(universityCollegeProfessionClassType)
	universityCollegeProfessionClassPrimaryKeyMapping, _ = queries.BindMapping(universityCollegeProfessionClassType, universityCollegeProfessionClassMapping, universityCollegeProfessionClassPrimaryKeyColumns)
	universityCollegeProfessionClassInsertCacheMut       sync.RWMutex
	universityCollegeProfessionClassInsertCache          = make(map[string]insertCache)
	universityCollegeProfessionClassUpdateCacheMut       sync.RWMutex
	universityCollegeProfessionClassUpdateCache          = make(map[string]updateCache)
	universityCollegeProfessionClassUpsertCacheMut       sync.RWMutex
	universityCollegeProfessionClassUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var universityCollegeProfessionClassBeforeInsertHooks []UniversityCollegeProfessionClassHook
var universityCollegeProfessionClassBeforeUpdateHooks []UniversityCollegeProfessionClassHook
var universityCollegeProfessionClassBeforeDeleteHooks []UniversityCollegeProfessionClassHook
var universityCollegeProfessionClassBeforeUpsertHooks []UniversityCollegeProfessionClassHook

var universityCollegeProfessionClassAfterInsertHooks []UniversityCollegeProfessionClassHook
var universityCollegeProfessionClassAfterSelectHooks []UniversityCollegeProfessionClassHook
var universityCollegeProfessionClassAfterUpdateHooks []UniversityCollegeProfessionClassHook
var universityCollegeProfessionClassAfterDeleteHooks []UniversityCollegeProfessionClassHook
var universityCollegeProfessionClassAfterUpsertHooks []UniversityCollegeProfessionClassHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UniversityCollegeProfessionClass) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range universityCollegeProfessionClassBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UniversityCollegeProfessionClass) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range universityCollegeProfessionClassBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UniversityCollegeProfessionClass) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range universityCollegeProfessionClassBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UniversityCollegeProfessionClass) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range universityCollegeProfessionClassBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UniversityCollegeProfessionClass) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range universityCollegeProfessionClassAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UniversityCollegeProfessionClass) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range universityCollegeProfessionClassAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UniversityCollegeProfessionClass) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range universityCollegeProfessionClassAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UniversityCollegeProfessionClass) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range universityCollegeProfessionClassAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UniversityCollegeProfessionClass) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range universityCollegeProfessionClassAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUniversityCollegeProfessionClassHook registers your hook function for all future operations.
func AddUniversityCollegeProfessionClassHook(hookPoint boil.HookPoint, universityCollegeProfessionClassHook UniversityCollegeProfessionClassHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		universityCollegeProfessionClassBeforeInsertHooks = append(universityCollegeProfessionClassBeforeInsertHooks, universityCollegeProfessionClassHook)
	case boil.BeforeUpdateHook:
		universityCollegeProfessionClassBeforeUpdateHooks = append(universityCollegeProfessionClassBeforeUpdateHooks, universityCollegeProfessionClassHook)
	case boil.BeforeDeleteHook:
		universityCollegeProfessionClassBeforeDeleteHooks = append(universityCollegeProfessionClassBeforeDeleteHooks, universityCollegeProfessionClassHook)
	case boil.BeforeUpsertHook:
		universityCollegeProfessionClassBeforeUpsertHooks = append(universityCollegeProfessionClassBeforeUpsertHooks, universityCollegeProfessionClassHook)
	case boil.AfterInsertHook:
		universityCollegeProfessionClassAfterInsertHooks = append(universityCollegeProfessionClassAfterInsertHooks, universityCollegeProfessionClassHook)
	case boil.AfterSelectHook:
		universityCollegeProfessionClassAfterSelectHooks = append(universityCollegeProfessionClassAfterSelectHooks, universityCollegeProfessionClassHook)
	case boil.AfterUpdateHook:
		universityCollegeProfessionClassAfterUpdateHooks = append(universityCollegeProfessionClassAfterUpdateHooks, universityCollegeProfessionClassHook)
	case boil.AfterDeleteHook:
		universityCollegeProfessionClassAfterDeleteHooks = append(universityCollegeProfessionClassAfterDeleteHooks, universityCollegeProfessionClassHook)
	case boil.AfterUpsertHook:
		universityCollegeProfessionClassAfterUpsertHooks = append(universityCollegeProfessionClassAfterUpsertHooks, universityCollegeProfessionClassHook)
	}
}

// One returns a single universityCollegeProfessionClass record from the query.
func (q universityCollegeProfessionClassQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UniversityCollegeProfessionClass, error) {
	o := &UniversityCollegeProfessionClass{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "user: failed to execute a one query for university_college_profession_class")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all UniversityCollegeProfessionClass records from the query.
func (q universityCollegeProfessionClassQuery) All(ctx context.Context, exec boil.ContextExecutor) (UniversityCollegeProfessionClassSlice, error) {
	var o []*UniversityCollegeProfessionClass

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "user: failed to assign all query results to UniversityCollegeProfessionClass slice")
	}

	if len(universityCollegeProfessionClassAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all UniversityCollegeProfessionClass records in the query.
func (q universityCollegeProfessionClassQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "user: failed to count university_college_profession_class rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q universityCollegeProfessionClassQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "user: failed to check if university_college_profession_class exists")
	}

	return count > 0, nil
}

// UniversityCollegeProfessionClasses retrieves all the records using an executor.
func UniversityCollegeProfessionClasses(mods ...qm.QueryMod) universityCollegeProfessionClassQuery {
	mods = append(mods, qm.From("`university_college_profession_class`"))
	return universityCollegeProfessionClassQuery{NewQuery(mods...)}
}

// FindUniversityCollegeProfessionClass retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUniversityCollegeProfessionClass(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*UniversityCollegeProfessionClass, error) {
	universityCollegeProfessionClassObj := &UniversityCollegeProfessionClass{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `university_college_profession_class` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, universityCollegeProfessionClassObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "user: unable to select from university_college_profession_class")
	}

	return universityCollegeProfessionClassObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UniversityCollegeProfessionClass) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("user: no university_college_profession_class provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(universityCollegeProfessionClassColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	universityCollegeProfessionClassInsertCacheMut.RLock()
	cache, cached := universityCollegeProfessionClassInsertCache[key]
	universityCollegeProfessionClassInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			universityCollegeProfessionClassAllColumns,
			universityCollegeProfessionClassColumnsWithDefault,
			universityCollegeProfessionClassColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(universityCollegeProfessionClassType, universityCollegeProfessionClassMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(universityCollegeProfessionClassType, universityCollegeProfessionClassMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `university_college_profession_class` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `university_college_profession_class` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `university_college_profession_class` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, universityCollegeProfessionClassPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "user: unable to insert into university_college_profession_class")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == universityCollegeProfessionClassMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "user: unable to populate default values for university_college_profession_class")
	}

CacheNoHooks:
	if !cached {
		universityCollegeProfessionClassInsertCacheMut.Lock()
		universityCollegeProfessionClassInsertCache[key] = cache
		universityCollegeProfessionClassInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the UniversityCollegeProfessionClass.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UniversityCollegeProfessionClass) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	universityCollegeProfessionClassUpdateCacheMut.RLock()
	cache, cached := universityCollegeProfessionClassUpdateCache[key]
	universityCollegeProfessionClassUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			universityCollegeProfessionClassAllColumns,
			universityCollegeProfessionClassPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("user: unable to update university_college_profession_class, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `university_college_profession_class` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, universityCollegeProfessionClassPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(universityCollegeProfessionClassType, universityCollegeProfessionClassMapping, append(wl, universityCollegeProfessionClassPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "user: unable to update university_college_profession_class row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "user: failed to get rows affected by update for university_college_profession_class")
	}

	if !cached {
		universityCollegeProfessionClassUpdateCacheMut.Lock()
		universityCollegeProfessionClassUpdateCache[key] = cache
		universityCollegeProfessionClassUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q universityCollegeProfessionClassQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "user: unable to update all for university_college_profession_class")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "user: unable to retrieve rows affected for university_college_profession_class")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UniversityCollegeProfessionClassSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("user: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), universityCollegeProfessionClassPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `university_college_profession_class` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, universityCollegeProfessionClassPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "user: unable to update all in universityCollegeProfessionClass slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "user: unable to retrieve rows affected all in update all universityCollegeProfessionClass")
	}
	return rowsAff, nil
}

var mySQLUniversityCollegeProfessionClassUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UniversityCollegeProfessionClass) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("user: no university_college_profession_class provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(universityCollegeProfessionClassColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLUniversityCollegeProfessionClassUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	universityCollegeProfessionClassUpsertCacheMut.RLock()
	cache, cached := universityCollegeProfessionClassUpsertCache[key]
	universityCollegeProfessionClassUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			universityCollegeProfessionClassAllColumns,
			universityCollegeProfessionClassColumnsWithDefault,
			universityCollegeProfessionClassColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			universityCollegeProfessionClassAllColumns,
			universityCollegeProfessionClassPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("user: unable to upsert university_college_profession_class, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "university_college_profession_class", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `university_college_profession_class` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(universityCollegeProfessionClassType, universityCollegeProfessionClassMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(universityCollegeProfessionClassType, universityCollegeProfessionClassMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "user: unable to upsert for university_college_profession_class")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == universityCollegeProfessionClassMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(universityCollegeProfessionClassType, universityCollegeProfessionClassMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "user: unable to retrieve unique values for university_college_profession_class")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, nzUniqueCols...)
	}

	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "user: unable to populate default values for university_college_profession_class")
	}

CacheNoHooks:
	if !cached {
		universityCollegeProfessionClassUpsertCacheMut.Lock()
		universityCollegeProfessionClassUpsertCache[key] = cache
		universityCollegeProfessionClassUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single UniversityCollegeProfessionClass record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UniversityCollegeProfessionClass) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("user: no UniversityCollegeProfessionClass provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), universityCollegeProfessionClassPrimaryKeyMapping)
	sql := "DELETE FROM `university_college_profession_class` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "user: unable to delete from university_college_profession_class")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "user: failed to get rows affected by delete for university_college_profession_class")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q universityCollegeProfessionClassQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("user: no universityCollegeProfessionClassQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "user: unable to delete all from university_college_profession_class")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "user: failed to get rows affected by deleteall for university_college_profession_class")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UniversityCollegeProfessionClassSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(universityCollegeProfessionClassBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), universityCollegeProfessionClassPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `university_college_profession_class` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, universityCollegeProfessionClassPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "user: unable to delete all from universityCollegeProfessionClass slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "user: failed to get rows affected by deleteall for university_college_profession_class")
	}

	if len(universityCollegeProfessionClassAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UniversityCollegeProfessionClass) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUniversityCollegeProfessionClass(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UniversityCollegeProfessionClassSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UniversityCollegeProfessionClassSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), universityCollegeProfessionClassPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `university_college_profession_class`.* FROM `university_college_profession_class` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, universityCollegeProfessionClassPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "user: unable to reload all in UniversityCollegeProfessionClassSlice")
	}

	*o = slice

	return nil
}

// UniversityCollegeProfessionClassExists checks if the UniversityCollegeProfessionClass row exists.
func UniversityCollegeProfessionClassExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `university_college_profession_class` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "user: unable to check if university_college_profession_class exists")
	}

	return exists, nil
}
