// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package user

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// UniversityCollegeProfession is an object representing the database table.
type UniversityCollegeProfession struct {
	ID           int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	UniversityID int         `boil:"university_id" json:"university_id" toml:"university_id" yaml:"university_id"`
	CollegeID    int         `boil:"college_id" json:"college_id" toml:"college_id" yaml:"college_id"`
	Name         string      `boil:"name" json:"name" toml:"name" yaml:"name"`
	Description  null.String `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`
	Status       null.Int8   `boil:"status" json:"status,omitempty" toml:"status" yaml:"status,omitempty"`
	Deleted      int8        `boil:"deleted" json:"deleted" toml:"deleted" yaml:"deleted"`
	Created      null.Time   `boil:"created" json:"created,omitempty" toml:"created" yaml:"created,omitempty"`
	CreatedUser  null.String `boil:"created_user" json:"created_user,omitempty" toml:"created_user" yaml:"created_user,omitempty"`
	Modified     null.Time   `boil:"modified" json:"modified,omitempty" toml:"modified" yaml:"modified,omitempty"`
	ModifiedUser null.String `boil:"modified_user" json:"modified_user,omitempty" toml:"modified_user" yaml:"modified_user,omitempty"`

	R *universityCollegeProfessionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L universityCollegeProfessionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UniversityCollegeProfessionColumns = struct {
	ID           string
	UniversityID string
	CollegeID    string
	Name         string
	Description  string
	Status       string
	Deleted      string
	Created      string
	CreatedUser  string
	Modified     string
	ModifiedUser string
}{
	ID:           "id",
	UniversityID: "university_id",
	CollegeID:    "college_id",
	Name:         "name",
	Description:  "description",
	Status:       "status",
	Deleted:      "deleted",
	Created:      "created",
	CreatedUser:  "created_user",
	Modified:     "modified",
	ModifiedUser: "modified_user",
}

// Generated where

var UniversityCollegeProfessionWhere = struct {
	ID           whereHelperint
	UniversityID whereHelperint
	CollegeID    whereHelperint
	Name         whereHelperstring
	Description  whereHelpernull_String
	Status       whereHelpernull_Int8
	Deleted      whereHelperint8
	Created      whereHelpernull_Time
	CreatedUser  whereHelpernull_String
	Modified     whereHelpernull_Time
	ModifiedUser whereHelpernull_String
}{
	ID:           whereHelperint{field: "`university_college_profession`.`id`"},
	UniversityID: whereHelperint{field: "`university_college_profession`.`university_id`"},
	CollegeID:    whereHelperint{field: "`university_college_profession`.`college_id`"},
	Name:         whereHelperstring{field: "`university_college_profession`.`name`"},
	Description:  whereHelpernull_String{field: "`university_college_profession`.`description`"},
	Status:       whereHelpernull_Int8{field: "`university_college_profession`.`status`"},
	Deleted:      whereHelperint8{field: "`university_college_profession`.`deleted`"},
	Created:      whereHelpernull_Time{field: "`university_college_profession`.`created`"},
	CreatedUser:  whereHelpernull_String{field: "`university_college_profession`.`created_user`"},
	Modified:     whereHelpernull_Time{field: "`university_college_profession`.`modified`"},
	ModifiedUser: whereHelpernull_String{field: "`university_college_profession`.`modified_user`"},
}

// UniversityCollegeProfessionRels is where relationship names are stored.
var UniversityCollegeProfessionRels = struct {
}{}

// universityCollegeProfessionR is where relationships are stored.
type universityCollegeProfessionR struct {
}

// NewStruct creates a new relationship struct
func (*universityCollegeProfessionR) NewStruct() *universityCollegeProfessionR {
	return &universityCollegeProfessionR{}
}

// universityCollegeProfessionL is where Load methods for each relationship are stored.
type universityCollegeProfessionL struct{}

var (
	universityCollegeProfessionAllColumns            = []string{"id", "university_id", "college_id", "name", "description", "status", "deleted", "created", "created_user", "modified", "modified_user"}
	universityCollegeProfessionColumnsWithoutDefault = []string{"name", "description", "created_user", "modified_user"}
	universityCollegeProfessionColumnsWithDefault    = []string{"id", "university_id", "college_id", "status", "deleted", "created", "modified"}
	universityCollegeProfessionPrimaryKeyColumns     = []string{"id"}
)

type (
	// UniversityCollegeProfessionSlice is an alias for a slice of pointers to UniversityCollegeProfession.
	// This should generally be used opposed to []UniversityCollegeProfession.
	UniversityCollegeProfessionSlice []*UniversityCollegeProfession
	// UniversityCollegeProfessionHook is the signature for custom UniversityCollegeProfession hook methods
	UniversityCollegeProfessionHook func(context.Context, boil.ContextExecutor, *UniversityCollegeProfession) error

	universityCollegeProfessionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	universityCollegeProfessionType                 = reflect.TypeOf(&UniversityCollegeProfession{})
	universityCollegeProfessionMapping              = queries.MakeStructMapping(universityCollegeProfessionType)
	universityCollegeProfessionPrimaryKeyMapping, _ = queries.BindMapping(universityCollegeProfessionType, universityCollegeProfessionMapping, universityCollegeProfessionPrimaryKeyColumns)
	universityCollegeProfessionInsertCacheMut       sync.RWMutex
	universityCollegeProfessionInsertCache          = make(map[string]insertCache)
	universityCollegeProfessionUpdateCacheMut       sync.RWMutex
	universityCollegeProfessionUpdateCache          = make(map[string]updateCache)
	universityCollegeProfessionUpsertCacheMut       sync.RWMutex
	universityCollegeProfessionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var universityCollegeProfessionBeforeInsertHooks []UniversityCollegeProfessionHook
var universityCollegeProfessionBeforeUpdateHooks []UniversityCollegeProfessionHook
var universityCollegeProfessionBeforeDeleteHooks []UniversityCollegeProfessionHook
var universityCollegeProfessionBeforeUpsertHooks []UniversityCollegeProfessionHook

var universityCollegeProfessionAfterInsertHooks []UniversityCollegeProfessionHook
var universityCollegeProfessionAfterSelectHooks []UniversityCollegeProfessionHook
var universityCollegeProfessionAfterUpdateHooks []UniversityCollegeProfessionHook
var universityCollegeProfessionAfterDeleteHooks []UniversityCollegeProfessionHook
var universityCollegeProfessionAfterUpsertHooks []UniversityCollegeProfessionHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UniversityCollegeProfession) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range universityCollegeProfessionBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UniversityCollegeProfession) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range universityCollegeProfessionBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UniversityCollegeProfession) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range universityCollegeProfessionBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UniversityCollegeProfession) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range universityCollegeProfessionBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UniversityCollegeProfession) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range universityCollegeProfessionAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UniversityCollegeProfession) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range universityCollegeProfessionAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UniversityCollegeProfession) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range universityCollegeProfessionAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UniversityCollegeProfession) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range universityCollegeProfessionAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UniversityCollegeProfession) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range universityCollegeProfessionAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUniversityCollegeProfessionHook registers your hook function for all future operations.
func AddUniversityCollegeProfessionHook(hookPoint boil.HookPoint, universityCollegeProfessionHook UniversityCollegeProfessionHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		universityCollegeProfessionBeforeInsertHooks = append(universityCollegeProfessionBeforeInsertHooks, universityCollegeProfessionHook)
	case boil.BeforeUpdateHook:
		universityCollegeProfessionBeforeUpdateHooks = append(universityCollegeProfessionBeforeUpdateHooks, universityCollegeProfessionHook)
	case boil.BeforeDeleteHook:
		universityCollegeProfessionBeforeDeleteHooks = append(universityCollegeProfessionBeforeDeleteHooks, universityCollegeProfessionHook)
	case boil.BeforeUpsertHook:
		universityCollegeProfessionBeforeUpsertHooks = append(universityCollegeProfessionBeforeUpsertHooks, universityCollegeProfessionHook)
	case boil.AfterInsertHook:
		universityCollegeProfessionAfterInsertHooks = append(universityCollegeProfessionAfterInsertHooks, universityCollegeProfessionHook)
	case boil.AfterSelectHook:
		universityCollegeProfessionAfterSelectHooks = append(universityCollegeProfessionAfterSelectHooks, universityCollegeProfessionHook)
	case boil.AfterUpdateHook:
		universityCollegeProfessionAfterUpdateHooks = append(universityCollegeProfessionAfterUpdateHooks, universityCollegeProfessionHook)
	case boil.AfterDeleteHook:
		universityCollegeProfessionAfterDeleteHooks = append(universityCollegeProfessionAfterDeleteHooks, universityCollegeProfessionHook)
	case boil.AfterUpsertHook:
		universityCollegeProfessionAfterUpsertHooks = append(universityCollegeProfessionAfterUpsertHooks, universityCollegeProfessionHook)
	}
}

// One returns a single universityCollegeProfession record from the query.
func (q universityCollegeProfessionQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UniversityCollegeProfession, error) {
	o := &UniversityCollegeProfession{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "user: failed to execute a one query for university_college_profession")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all UniversityCollegeProfession records from the query.
func (q universityCollegeProfessionQuery) All(ctx context.Context, exec boil.ContextExecutor) (UniversityCollegeProfessionSlice, error) {
	var o []*UniversityCollegeProfession

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "user: failed to assign all query results to UniversityCollegeProfession slice")
	}

	if len(universityCollegeProfessionAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all UniversityCollegeProfession records in the query.
func (q universityCollegeProfessionQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "user: failed to count university_college_profession rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q universityCollegeProfessionQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "user: failed to check if university_college_profession exists")
	}

	return count > 0, nil
}

// UniversityCollegeProfessions retrieves all the records using an executor.
func UniversityCollegeProfessions(mods ...qm.QueryMod) universityCollegeProfessionQuery {
	mods = append(mods, qm.From("`university_college_profession`"))
	return universityCollegeProfessionQuery{NewQuery(mods...)}
}

// FindUniversityCollegeProfession retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUniversityCollegeProfession(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*UniversityCollegeProfession, error) {
	universityCollegeProfessionObj := &UniversityCollegeProfession{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `university_college_profession` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, universityCollegeProfessionObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "user: unable to select from university_college_profession")
	}

	return universityCollegeProfessionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UniversityCollegeProfession) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("user: no university_college_profession provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(universityCollegeProfessionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	universityCollegeProfessionInsertCacheMut.RLock()
	cache, cached := universityCollegeProfessionInsertCache[key]
	universityCollegeProfessionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			universityCollegeProfessionAllColumns,
			universityCollegeProfessionColumnsWithDefault,
			universityCollegeProfessionColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(universityCollegeProfessionType, universityCollegeProfessionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(universityCollegeProfessionType, universityCollegeProfessionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `university_college_profession` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `university_college_profession` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `university_college_profession` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, universityCollegeProfessionPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "user: unable to insert into university_college_profession")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == universityCollegeProfessionMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "user: unable to populate default values for university_college_profession")
	}

CacheNoHooks:
	if !cached {
		universityCollegeProfessionInsertCacheMut.Lock()
		universityCollegeProfessionInsertCache[key] = cache
		universityCollegeProfessionInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the UniversityCollegeProfession.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UniversityCollegeProfession) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	universityCollegeProfessionUpdateCacheMut.RLock()
	cache, cached := universityCollegeProfessionUpdateCache[key]
	universityCollegeProfessionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			universityCollegeProfessionAllColumns,
			universityCollegeProfessionPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("user: unable to update university_college_profession, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `university_college_profession` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, universityCollegeProfessionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(universityCollegeProfessionType, universityCollegeProfessionMapping, append(wl, universityCollegeProfessionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "user: unable to update university_college_profession row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "user: failed to get rows affected by update for university_college_profession")
	}

	if !cached {
		universityCollegeProfessionUpdateCacheMut.Lock()
		universityCollegeProfessionUpdateCache[key] = cache
		universityCollegeProfessionUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q universityCollegeProfessionQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "user: unable to update all for university_college_profession")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "user: unable to retrieve rows affected for university_college_profession")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UniversityCollegeProfessionSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("user: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), universityCollegeProfessionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `university_college_profession` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, universityCollegeProfessionPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "user: unable to update all in universityCollegeProfession slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "user: unable to retrieve rows affected all in update all universityCollegeProfession")
	}
	return rowsAff, nil
}

var mySQLUniversityCollegeProfessionUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UniversityCollegeProfession) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("user: no university_college_profession provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(universityCollegeProfessionColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLUniversityCollegeProfessionUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	universityCollegeProfessionUpsertCacheMut.RLock()
	cache, cached := universityCollegeProfessionUpsertCache[key]
	universityCollegeProfessionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			universityCollegeProfessionAllColumns,
			universityCollegeProfessionColumnsWithDefault,
			universityCollegeProfessionColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			universityCollegeProfessionAllColumns,
			universityCollegeProfessionPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("user: unable to upsert university_college_profession, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "university_college_profession", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `university_college_profession` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(universityCollegeProfessionType, universityCollegeProfessionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(universityCollegeProfessionType, universityCollegeProfessionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "user: unable to upsert for university_college_profession")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == universityCollegeProfessionMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(universityCollegeProfessionType, universityCollegeProfessionMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "user: unable to retrieve unique values for university_college_profession")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, nzUniqueCols...)
	}

	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "user: unable to populate default values for university_college_profession")
	}

CacheNoHooks:
	if !cached {
		universityCollegeProfessionUpsertCacheMut.Lock()
		universityCollegeProfessionUpsertCache[key] = cache
		universityCollegeProfessionUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single UniversityCollegeProfession record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UniversityCollegeProfession) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("user: no UniversityCollegeProfession provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), universityCollegeProfessionPrimaryKeyMapping)
	sql := "DELETE FROM `university_college_profession` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "user: unable to delete from university_college_profession")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "user: failed to get rows affected by delete for university_college_profession")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q universityCollegeProfessionQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("user: no universityCollegeProfessionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "user: unable to delete all from university_college_profession")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "user: failed to get rows affected by deleteall for university_college_profession")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UniversityCollegeProfessionSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(universityCollegeProfessionBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), universityCollegeProfessionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `university_college_profession` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, universityCollegeProfessionPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "user: unable to delete all from universityCollegeProfession slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "user: failed to get rows affected by deleteall for university_college_profession")
	}

	if len(universityCollegeProfessionAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UniversityCollegeProfession) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUniversityCollegeProfession(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UniversityCollegeProfessionSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UniversityCollegeProfessionSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), universityCollegeProfessionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `university_college_profession`.* FROM `university_college_profession` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, universityCollegeProfessionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "user: unable to reload all in UniversityCollegeProfessionSlice")
	}

	*o = slice

	return nil
}

// UniversityCollegeProfessionExists checks if the UniversityCollegeProfession row exists.
func UniversityCollegeProfessionExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `university_college_profession` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "user: unable to check if university_college_profession exists")
	}

	return exists, nil
}
